# This is an example neoforge.neoforge.mods.toml file. It contains the data relating to the loading mods.
# There are several mandatory fields (#mandatory), and many more that are optional (#optional).
# The overall format is standard TOML format, v0.5.0.
# Note that there are a couple of TOML lists in this file.
# Find more information on toml format here:  https://github.com/toml-lang/toml
# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml" #mandatory

# A version range to match for said mod loader - for regular FML @Mod it will be the FML version. This is currently 2.
loaderVersion="[2,]" #mandatory

# The license for you mod. This is mandatory metadata and allows for easier comprehension of your redistributive properties.
# Review your options at https://choosealicense.com/. All rights reserved is the default copyright stance, and is thus the default here.
license="MIT"

# A URL to refer people to when problems occur with this mod
issueTrackerURL="https://discord.gg/WsuFsGSegD" #optional

# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory

modId="starcatcher"
version="${mod_version}"
displayName="${mod_name}"
displayURL="http://curseforge.com/minecraft/mc-mods/starcatcher"
logoFile="starcatcher 256x256.png" #optional
authors="${authors}" #optional
description='''A fishing mod with lots of fishes to collect!
Big thank you to Kapitencraft, Quarris, Kaupenjoe's discord community and Neoforge discord community!

Credits:
wdiscute - Main Developer

Nikdo53 - Fishing minigame art, tweaked all fish sprites

ScribbleDemon - Guide book, fish spotter and "Fish Caught!" notification art

DayTheMagpie - Fish Trophies Models

Spring - 3d Fish models
'''

[[mixins]]
config="starcatcher.mixins.json"

# In neoforge.mods.toml:
[[accessTransformers]]
file="META-INF/accesstransformer.cfg"

[[dependencies.starcatcher]] #optional
modId="neoforge" #mandatory
type="required" #mandatory
versionRange="${neo_version_range}" #mandatory
ordering="AFTER"
side="BOTH"

# Here's another dependency
[[dependencies.starcatcher]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="AFTER"
side="BOTH"
